# initial yml
# defines a sequence generatot for message data
# as used in the main coap service
# meant to create a varying sequence of events to create
# test databases for data visualisation etc

# timeLine
#-------------------------------------------------------------------------------- 
# startOffset's are in %, therefore 0.1 represents 0.1%
# of the entire sequence as a start position for the block. 
#
# e.g.
# if maxInterval: 1000 and an offset value was 0.1 the offset
# would represent 1 interval because 1000/100/10 = 1 so the 
# eventBlock would begin after 1 timeIntervalSeconds had passed.
#
# each timeLine can be only one data type but there can be multiple
# timeLines, just add a new block

# TODO refactor to use anchors and overrides...
timeLines:
  dataXPOS: &timeline_definition
    startTime: time string
    timeInterval: 10m
    maxIntervals: 10000
    initialValue: 5.67
    driftFactor: 0.01
    maxAllowedDrift: 0.1
    eventBlocks:
      event1: &eventblock_definition
        eventName: drift in x
        startOffset: 0.1
        endOffset:
        driftFactor:
        maxAllowedDrift:
        timeInterval:
        resetAfterEvent: true
  YPOSData:
    <<: *timeline_definition
    initialValue: 6.21
    driftFactor: 0.2
    eventBlocks:
      event1:
        <<: *eventblock_definition
        eventName: drift in Y
        startOffset: 0.5
